src/utils/dark.ts

Just a minor simplification. I prefer the following over selecting the root element:
```diff
-const html = document.getElementsByTagName('html')[0]
+const html = document.documentElement
```
Thanks for your work on this starter project!

Simplify html selector

---

index.html
public/favicon.svg

This pull request adds dark mode support to the SVG favicon. Its path stays the same. Vector favicons are:
- future-proof
- resolution-agnostic – they look crisp regardless of how large the displays is
- quite small
Since CSS media queries are available inside the SVG files, `prefers-color-scheme` helps to provide support for dark mode.
No related issues found.

SVG favicon with dark mode support 

---

package.json

Vite doesn't have -p shorthand for port option.

fix: port option

---

netlify.toml

Hi, this will prevent netlify automatic install npm dependencies., can save build time.

chore: skip netlify automatic npm install

---

.vscode/extensions.json

`antfu.i18n-ally` got renamed to `lokalise.i18n-ally,` but `.vscode/extensions.json` hasn't been changed to reflect it yet.
This prompts Visual Studio Code to recommend you to install `antfu.i18n-ally` despite being deprecated.
- Replace `antfu.i18n-ally` with `lokalise.i18n-ally`.

chore: update i18n-ally vscode extension

---

src/pages/index.vue

This change fixes a bug in the main page where if you enter your name as a url or something similar it will redirect you to a 404.
This isn't exactly essential as when a user clones this template they will most likely replace all of these files, but for the sake of completeness I thought it might be a good idea to fix this. 
**Current Problem**
index.ts; line 9
```ts 
const go = () => {
if (name.value)
router.push(`/hi/${name.value}`)
}
```
If you enter something like `https://github.com/antfu/vitesse` you will be redirected to a 404 page
**Solution**
index.ts; line 9
```ts
const go = () => {
if (name.value)
router.push(`/hi/${encodeURIComponent(name.value)}`)
}
```
This will result in `Hi, https://github.com/antfu/vitesse!`
This is just a small bug I ran into during the development of a …

fix: EncodeURIComponent for dynamic name route

---

vite.config.ts

No need for that, as that is default behavior of `vite-plugin-pages`
>importMode
Import mode can be set to either async, sync, or a function which returns one of those values.
Default:
Top level index file: 'sync'
Others: 'async'

chore: update vite.config.ts

---

tailwind.config.js

Hey,
Some variants like focus for background colours was not working for me while I was using Vitesse, it's because the variants key in the tailwind config file does not have extend with it. So things like,
```
<input class="bg-red-600 focus:g-green-600" /> 
```
won't work because the focus variant is not enabled in the config file.
In this PR I have added `extend` key to tailwind variants config and included only the extra variants that are needed for Vitesse.

fix: added extend key to tailwind variants

---

src/shims-md.d.ts
src/shims-vue.d.ts

see https://github.com/vuejs/vue-next-webpack-preview/issues/5#issuecomment-579823346
It has no effect to use, but there's always a `TS` red wavy line which is annoying
and we may lose the ability to  locate the `.vue` file in `.ts`

chore: update shims-vue.d.ts

---

src/styles/main.postcss

Currently the template has `width: 100vw` on the body, but this causes a horizontal overflow whenever there is a vertical overflow. Removing this doesn't seem to negatively affect anything and prevents a horizontal overflow whenever there is a vertical overflow

fix: horizontal overflow scrollbar when vertical scrollbar appears

---

index.html
vite.config.ts

Fixed missing `apple-touch-icon` entry on `index.html`.
Fixed missing `maskable icon` entry on `manifest.webmanifest` generated file on `vite.config.ts` configuration file.

Make lighthouse PWA compliant

---

.vscode/settings.json
src/pages/hi/[name].vue
src/shims.d.ts

volar 0.21.0 supported ts plugin with vscode setting and default disabled.
this pr support enabled ts plugin in user workspace.
note: will broke some users don't use volar.

feat: enable volar ts plugin

---

locales/fr.json
package.json
pnpm-lock.yaml
src/layouts/default.vue
src/layouts/home.vue
src/main.ts
src/styles/tw-base.postcss
src/styles/tw-components.postcss
src/styles/tw-utilities.postcss

Hi @antfu  - While I appreciate the goal of windicss to allow instant loading of tailwind, I'm not a big fan of moving away from the official TW builds and code.  I feel like windicss will be forever trying to catch up with TW and all of the edge cases.
Would it be OK if I help maintain the Tailwind branch?
I also implemented a different way to load Tailwind that dramatically improves HMR updates, even if it doesn't do anything to solve the initial build time.
https://github.com/tailwindlabs/tailwindcss/issues/2820

chore: updates

---

src/shims.d.ts

Fixes `import App from './App.vue'` throwing ts2307: cannot find module (in `/src/main.ts` and others)

fix: vue file imports throwing IDE errors

---

src/styles/main.css

in some browsers (e.g. ios safari) `100vh` will extend beyond a users viewport because the address bar is considered for the calculation of the value. Changing to 100% fixes that.
see issue #111

fix: layout higher than display

---

locales/fr.yml

Hi,
I submit a small pull request here to fix the french translation.
Two of the fixes are just typos, the third (`Maison` -> `Accueil`) could need an explanation so here it is:
"Maison" in french is your "home building" but "Accueil" is usuallty the wordig on french website to indicate that this link redirect to the root page of the app. Since the icon used is actually a tepee maybe you called this link "Maison" on purpose, so let me know if you need me to remove this third change.
Thanks

i18n: improve french translation

---

package.json
pnpm-lock.yaml
vite.config.ts

Add `_blank` for all links with `http://` / `https://`.
I think it's useful for writing links in markdown.

feat(md): add _blank for all links with http/https

---

.gitignore
src/pages/about.md
src/styles/markdown.css
vite.config.ts

- add dark mode for markdown `blockquote`
- set var `markdownWrapperClasses` for plugin Markdown `wrapperClasses` and WindiCSS `safelist`
- add `*.log` for `.gitignore` (Because `pnpm-debug.log` appears when `pnpm` installation failed)

chore: support blockquote dark mode & simplify markdown wrapper

---

README.md

The link for the icon feature was pointing to the location for components auto importing.

fix: feature list link for icons was incorrect

---

vite.config.ts

- https://github.com/intlify/vite-plugin-vue-i18n is deprecated and move to https://github.com/intlify/bundle-tools/tree/main/packages/vite-plugin-vue-i18n

chore: update vite-plugin-vue-i18n link

---

index.html

The script at the end of `<body>` to handle light/dark theming is called when the inlined CSS styles have already been loaded. This sometimes leads to flickering. 
With this change, the script to set theme mode will always be called first, since critter embeds the CSS at the end of `<head>`. What do you think?

fix: theme color flickering w/ critters

---

.vscode/settings.json

I was testing out this template and noticed some fighting in VSCode in my editor. I had `editor.formatOnSave` on true in my global settings, and as this was not disabled in the workspace first ESlint did its autoformatting and after that VSCode did it's formatting. This causes issues with spacing/tabs etc.
Explicitely disabling this settings in the template will prevent this from happening :)

fix: formatOnSave not disabled in workspace

---

README.md

This pull request proposes to reference my own variation of `vitesse` and `vitesse-stackter-clean-architect` and focuses on adding strong out of the box linting and formatting.
Code style is verified on pre-commit. Component and E2E tests run on-pre-push.
As a bonus, the pull request also adds bug, user story and pull request templates for github. These are also added for gitlab with a gitlab CI/CD script.

docs: add new vitesse community variation

---

src/shims.d.ts

Helps get rid of eslint error when importing Vue components from relative path. It happens for example in `main.js` where:
```
import App from './App.vue'
```
gives us an error, stating `Cannot find module './App.vue' or its corresponding type declarations.ts(2307)`. Hope it gets merged.

chore: add vue shims for better eslint linting

---

src/main.ts

In the current setup, we don't pass the `base` property to the `RouterOptions` in the `ViteSSG` function. The result is that [vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages) will not work when a base URL is set in the `vite.config.ts` file.

fix: pass BASE_URL to ViteSSG

---

src/main.ts

Map will create a new array, but you don't need it here

chore: change the map to foreach

---

package.json
pnpm-lock.yaml
src/auto-imports.d.ts
src/components.d.ts

Maybe we do not need add them in `devDependencies`, because they are dependencies of vue.
> Note: as of 3.2.13+, this package is included as a dependency of the main vue package and can be accessed as vue/compiler-sfc. This means you no longer need to explicitly install this package and ensure its version match that of vue's. Just use the main vue/compiler-sfc deep import instead.
> https://github.com/vuejs/core/tree/main/packages/compiler-sfc

chore: remove @vue/{compiler-sfc, server-renderer}

---

README.md

Forked vitesse-lite but for React https://github.com/lxy-yz/vitesse-lite-react [live demo](https://vitesse-lite-react.netlify.app/)

chore: add React fork of vitesse-lite to readme

---

package.json
pnpm-lock.yaml

`@unocss/reset` seems to be already depended on by `unocss`, I guess we don't need to put it in package.json.

chore: remove @unocss/reset dependencies

---

.vscode/extensions.json

This is likely a good idea considering we use `cSpell.words` in the `settings.json`
Thanks for this great started kit!

Adds `code-spell-checker` to recommendations

---

README.md

add two line breaks to make markdown rendered correctly.
before:

fix: the heading 2 is rendered correctly

---

.editorconfig

Hi Antfu, I added an `.editorconfig` file to be able to override the editor's default settings.
For example, if the default indent size of the editor is 4 spaces, when I press tab, the editor will indent with 4 spaces, and then when I save, it will be formatted to 2 spaces again by eslint, which is not a friendly experience.
---
我添加了一个 `.editorconfig` 文件，以便能覆盖编辑器的默认设置。
比如缩进设置，如果编辑器默认缩进大小是 4 空格，当我按 tab 时，编辑器会以 4 空格进行缩进，然后保存时，通过 eslint 再格式化成 2 空格，体验不够友好。

feat: add `.editorconfig` file

---

Dockerfile
README.md

Hi Anthony. I added a dockerfile for the vitesse template with adequate documentation of usage in the markdown. hope this helps,

feat(deployment): docker file for vitesse

---

README.md

the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled

docs: update docker build command

---

README.md
README.zh-CN.md

- link of `vue-router` should point to v4 instead of v3
- link of `vite-plugin-vue-i18n` is outdated
- link of `volar` still works by redirection but it's always good to keep things up to date 😆

docs: update links

---

README.md
README.zh-CN.md
src/modules/pinia.ts

Pinia's links have been redirected

docs: update pinia links

---

package.json
pnpm-lock.yaml

I think since `@unocss/reset` is used in [main](https://github.com/antfu/vitesse/blob/main/src/main.ts#L7),  I guess we need to put it in package.json.
Remove PR: https://github.com/antfu/vitesse/pull/332

chore: add @unocss/reset dependencies

---

README.md

In "Features", the component preview link was leading to a dead link. 
I changed the link to be the same as the one in the "Plugins" section.

docs: correct link to Component Preview repository on "Features"

---

.github/workflows/ci.yml

The e2e tests failed due to Vite optimizing the dependencies in the dev mode. When Vite optimizes the dependencies, the page will reload. 
Set the start command to`npx vite preview --port 3333` to start the production build and prevent Vite optimizes the dependencies during testing.
Here are the simulation steps of test `markdown`:
click on the `about` link
check if URL is equal to `/about`
[vite] ✨ optimized dependencies changed. reloading
(page load)--page loaded--    -> localhost:3333/
check timeout -> test fail
1. open cypress
2. run a spec, then configure the network option to `Slow 3G` or `Fast 3G` in the dev tool
4. run `vite --port 3333 --force`
5. restart the test
none
none

ci: use `vite preview` to start prod build

---

README.md
README.zh-CN.md

update unplugin-auto-import url to https://github.com/unplugin/unplugin-auto-import

chore: update url

---

Dockerfile

https://docs.docker.com/reference/build-checks/from-as-casing/
This PR fixes the [FromAsCasing](https://docs.docker.com/reference/build-checks/from-as-casing/) warning.
Related https://github.com/antfu/vitesse-nuxt/pull/128

fix: align docker FromAsCasing

---

Dockerfile

This PR fixes the Docker build by copying `pnpm-workspace.yaml` required for pnpm catalog dependency resolution.

fix: copy `pnpm-workspace.yaml` for docker build catalog resolution

---

vite.config.ts

Modified the registration location of the `unplugin-vue-router` plugin 
It needs to be registered before 'vue'
fixes #551

fix: error occurred when using `definePage`
