- locales/fr.json
I made a few changes to the french translations (because they were very Google-translatey). 
There's no good equivalent in french for "opinionated" (dogmatique is technically correct but not really in this context) so I changed the translation to something that means "Vite application example" in english. 
By the way, excellent work on Vitesse, it's pretty amazing.
> i18n(fr): correct translations

- locales/vi.json
- src/messages.ts
Hi, I made a translation in vietnammese, hope you can merge it!
> i18n(vi): add vietnamese translation

- package.json
- pnpm-lock.yaml
- tsconfig.json
https://github.com/vitejs/vite/commit/245303ca35ff2a40eca49e102b4f82cb1210f597
> fix: add vite client types & update dependencies

- locales/es.json
Updated Spanish translations to match [the current English version](https://github.com/antfu/vitesse/commit/edec07ad444de488fac8981458c10803719b60a7#diff-c9218bed23f0aeb93d7e1a7d5f6e1345fae20f4b8692b27fb97fd0f37b3d26d7) at the time of the PR.
> chore: update spanish translations

- locales/ko.json
I added locale for Korean users. :)
> feat(i18n): add ko.json

- locales/tr.json
I added locale for Türkiye users. :)
> feat(i18n): add tr.json

- locales/it.json
> feat(i18n): add it.json

- vite.config.ts
since vite-plugin-pages 0.4.6, need add replaceSquareBrackets: false to config,
> fix: update vite-plugin-pages config

- locales/rodgeraraujo/pt-BR.json
I added locale for Brazilian users.
> feat(i18n): add pt-BR.json

- src/main.ts
As shown in the vite-plugin-vue readme
> refactor: import setupLayouts from virtual module

- vite.config.ts
> fix: add missing assets to sw to work offline

- vite.config.ts
> chore: optimize vue-i18n

- locales/de.yml
Self-explanatory.
On a side-note: I'm constantly amazed by the projects you create. Happy follower of your work! I'm learning a lot. 🙇‍♂️
> chore(lang): add missing German translation string

- package.json
- pnpm-lock.yaml
- vite.config.ts
- use `@types/markdown-it-link-attributes`
> fix: add type for markdown-it-link-attributes

- README.md
thankyou! i inspired this template from vitesse.
> Adding my own opinionated template

- README.md
Added a new variant in the readme from this discussion https://github.com/antfu/vitesse/discussions/231
> docs: add new variant

- README.md
> chore: remove unnecessary checklist item

- package.json
- src/modules/i18n.ts
- src/modules/nprogress.ts
- src/modules/pinia.ts
- src/modules/pwa.ts
- src/shims.d.ts
- src/types.ts
> chore: add type for import by eslint

- vite.config.ts
Update resolver configuration with proper K/V pair, as current implementation is deprecated.
> chore(IconsResolver): update deprecated property

- README.md
Check https://github.com/antfu/vite-ssg/pull/186
> docs: update SSG acronym

- src/modules/README.md
- Updated `modules/README.md` to reflect the type in import
> chore: update `README.md` to reflect type for import

- README.md
i inspired this template from vitesse.
it likes Vitesse but without SSG/SSR/File based routing, includes ESLint Prettier/Airbnb Style/Element Plus.
> docs: new template vitecamp

- src/modules/nprogress.ts
- When we jump in a page by hash, I think we do not need nprogress start.
> feat: only start nprogress when to from different

- locales/ar.yml
Adding new yaml file containing the Arabic translations
> add arabic language

- src/shims.d.ts
Just came across this minimal improvement and figured to PR it.
Thanks!
> Slightly adjust the `vite-plugin-md` comment

- index.html
- src/App.vue
We can dynamically switch `theme-color` with dark mode.
> feat: toggle meta theme-color with mode

- README.md
- README.zh-CN.md
- package.json
- pnpm-lock.yaml
- vite.config.ts
Hope it helps with user development experience.  🙏
Close the PR directly if you don't think it's necessary, thx ! 😊
> feat: add vite-plugin-vue-inspector plugin

- index.html
- public/favicon-dark.svg
- public/favicon.svg
- src/App.vue
- src/composables/dark.ts
> fix: favicon dark mode

- src/layouts/default.vue
- src/layouts/home.vue
- src/pages/hi/[name].vue
- unocss.config.ts
Feel free to remove this PR if you think this is not a necessary
> fix: improve lighthouse accessibility

- README.md
- README.zh-CN.md
https://github.com/vitejs/vite/issues/9113
> docs: update node requirement

- package.json
- pnpm-lock.yaml
Upgrade vite-plugin-vue-layouts 0.7.0
> chore: upgrade vite-plugin-vue-layouts

- README.md
https://github.com/YunYouJun/vitesse-h5
There are also some more appropriate strategies and practices for mobile.
So I created this template to document what I think are the best practices for mobile web apps, inspired by [vitesse](https://github.com/antfu/vitesse).
> chore: add new community project for readme

- README.md
vue is awesome, but solidjs is my first real love: give it a try!
This is not solving anything, only adding a community version using SolidJS instead of vue3
-- none
You can go visit the repo there => [🦇](https://github.com/olgam4/bat)
> docs: added bat to the community versions

- README.md
Fix https://github.com/antfu/vitesse/pull/386#discussion_r978219802
https://github.com/antfu/vitesse/pull/386#discussion_r978219802
> docs: readme was incorrectly changed by #386

- netlify.toml
Remove pnpm workaround for netlify
https://twitter.com/pnpmjs/status/1582388200504365056
> chore: remove pnpm workaround for netlify

- README.zh-CN.md
> chore: typo

- README.md
- README.zh-CN.md
> chore: doc update

- README.md
docs: upgrade vite-plugin-vue-i18n to unplugin-vue-i18n
> docs: upgrade vite-plugin-vue-i18n to unplugin-vue-i18n

- vite.config.ts
upgrade unplugin-vue-i18n reference link
> chore: upgrade unplugin-vue-i18n reference link

- README.md
[vitesse-solid](https://github.com/xbmlz/vitesse-solid) , Inspired by vitesse, build with [`SolidStart`](https://start.solidjs.com/), includes [UnoCSS](https://github.com/unocss/unocss) and [HopeUI](https://hope-ui.com/).
- **Fine-grained reactivity**. Since SolidStart is a SolidJS meta-framework, it benefits from the fine-grained reactivity offered by SolidJS.
- **Isomorphic, nested routing**. You write the same routes regardless of whether the page is rendered on the client or server. Route nesting provides parent-child relationships that simplify application logic.
- **Multiple rendering modes**. SolidStart can be used to create CSR, SSR, streaming SSR, or SSG applications.
- **Command Line Interface (CLI) and templates**. Get up and running quickly with starters.
- **Deployment …
> docs: add new community template

- index.html
- This pull request will alert a message just in case Javascript is not supported in browser which is being used.
--
--
> feat: add `<noscript>` message

- README.md
- README.zh-CN.md
- src/pages/index.vue
- vite.config.ts
Removing deprecated/dropped reactivity transform feature support
https://github.com/vuejs/rfcs/discussions/369
> refactor: remove deprecated reactivity transform

- vite.config.ts
> docs: update uno comments in vite.config.ts

- locales/uz.yml
Added Uzbek language
I'm just adding language support to `locales`. 
No any linked issues.
> feat(lang): Add Uzbek language

- src/pages/index.vue
This PR localizes the index page placeholder text to match the user's language setting.
none
> fix: dynamic placeholder

- README.md
- README.zh-CN.md
- package.json
- pnpm-lock.yaml
- vite.config.ts
add `vite-plugin-vue-devtools`
> feat: add `vue-devtools` plugin

- src/pages/hi/[name].vue
fix missing dynamic route parameters
https://github.com/antfu/vitesse/issues/514
> fix: dynamic route parameters

- .github/workflows/ci.yml
update Github Actions version to remove Actions warning of using node16
> chore: update action version

- uno.config.ts
Add missing class for the MDC plugin to the safelist.
https://github.com/antfu/vitesse/blob/acd960e6bc40b42703cd966287b3428ed3718715/vite.config.ts#L82
N/A
N/A
> fix: add missing safelist class

- README.md
Update `README.md` from `Nuxt 3` to `Nuxt 4`
n/a
n/a
> chore: update readme to recommend nuxt 4
